/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VehicleBooking;

import Business.EcoSystem;
import Business.Transportation.VehicleBooking.Vehicle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siddh
 */
public class ManageVehiclePanel extends javax.swing.JPanel {
    private EcoSystem system;

    /**
     * Creates new form ManageVehicle
     */
    public ManageVehiclePanel(EcoSystem system) {
        initComponents();
        this.system = system;
        
        populateTable();
    }
    
    private void resetVehicleData() {
        txtCategory.setText("");
        txtVehicleName.setText("");
        txtVehicleNum.setText("");
        txtSeater.setText("");
        txtPrice.setText("");
    }
    
     private void populateTable() {
        //new test
         
         DefaultTableModel model = (DefaultTableModel) tblVehicle.getModel();
        
        model.setRowCount(0);

        for (Vehicle vehicle : system.getVehicleDirectory().getVehicleDirectory() ) {
            Object[] row = new Object[5];

            row[0] = vehicle;
            row[1] = vehicle.getVehicleName();
            row[2] = vehicle.getCategory();
            row[3] = vehicle.getSeater();
            row[4] = vehicle.getPrice();
            

            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtVehicleName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVehicleNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnAddVehicle = new javax.swing.JButton();
        btnDeleteVehicle = new javax.swing.JButton();
        btnViewVehicle = new javax.swing.JButton();
        btnUpdateVehicle = new javax.swing.JButton();
        txtCategory = new javax.swing.JTextField();
        txtSeater = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicle = new javax.swing.JTable();

        jLabel1.setText("MANAGE VEHICLES");

        jLabel2.setText("Vehicle Name");

        jLabel3.setText("Vehicle Number");

        jLabel4.setText("Seater");

        jLabel5.setText("Category");

        jLabel6.setText("Price per hour ($)");

        btnAddVehicle.setText("ADD");
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });

        btnDeleteVehicle.setText("DELETE");
        btnDeleteVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVehicleActionPerformed(evt);
            }
        });

        btnViewVehicle.setText("VIEW");
        btnViewVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVehicleActionPerformed(evt);
            }
        });

        btnUpdateVehicle.setText("UPDATE");
        btnUpdateVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVehicleActionPerformed(evt);
            }
        });

        tblVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vehicle Number", "Vehicle Name", "Category", "Seater", "Price per hour"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVehicle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVehicleName)
                            .addComponent(txtCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVehicleNum)
                            .addComponent(txtSeater, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                        .addGap(406, 406, 406))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(330, 330, 330)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnDeleteVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnViewVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnUpdateVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtVehicleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddVehicle)
                            .addComponent(btnDeleteVehicle)
                            .addComponent(btnViewVehicle)
                            .addComponent(btnUpdateVehicle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
        // TODO add your handling code here:
        String vehicleName = txtVehicleName.getText();
        String vehicleNumber = txtVehicleNum.getText();
        String category = txtCategory.getText();
        Integer seater = Integer.parseInt(txtSeater.getText());
        Integer price = Integer.parseInt(txtPrice.getText());
        
        Vehicle vehicle = system.getVehicleDirectory().addVehicleDetails();
        vehicle.setVehicleName(vehicleName);
        vehicle.setVehicleNumber(vehicleNumber);
        vehicle.setPrice(price);
        vehicle.setSeater(seater);
        vehicle.setCategory(category);
        
        JOptionPane.showMessageDialog(this, "Vehicle added");
        resetVehicleData();
        populateTable();
    }//GEN-LAST:event_btnAddVehicleActionPerformed

    private void btnDeleteVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVehicleActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblVehicle.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row for deletion");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblVehicle.getModel();
        Vehicle selectedVehicle = (Vehicle) model.getValueAt(selectedRowIndex, 0);

        system.getVehicleDirectory().deleteVehicle(selectedVehicle);

        JOptionPane.showMessageDialog(this, "Vehicle Deleted");

        populateTable();
    }//GEN-LAST:event_btnDeleteVehicleActionPerformed

    private void btnViewVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVehicleActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tblVehicle.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row for viewing");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblVehicle.getModel();
        Vehicle selectedVehicle = (Vehicle) model.getValueAt(selectedRowIndex, 0);
        
        txtVehicleNum.setText(selectedVehicle.getVehicleNumber());
        txtVehicleName.setText(selectedVehicle.getVehicleName());
        txtCategory.setText(selectedVehicle.getCategory());
        txtSeater.setText(String.valueOf(selectedVehicle.getSeater()));
        txtPrice.setText(String.valueOf(selectedVehicle.getPrice()));
        
    }//GEN-LAST:event_btnViewVehicleActionPerformed

    private void btnUpdateVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVehicleActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tblVehicle.getModel();

           if (tblVehicle.getSelectedRowCount() == 1) {
            
            String vehicleNumber = txtVehicleNum.getText();
            String vehicleName = txtVehicleName.getText();
            int seater = Integer.parseInt(txtSeater.getText());
            int price = Integer.parseInt(txtPrice.getText());
            String category = txtCategory.getText();
            
            
            int selectedRowIndex = tblVehicle.getSelectedRow();
        Vehicle vehicle = system.getVehicleDirectory().getVehicles(selectedRowIndex);
            
            
        vehicle.setVehicleNumber(vehicleNumber);
        vehicle.setVehicleName(vehicleName);
        vehicle.setCategory(category);
        vehicle.setSeater(seater);
        vehicle.setPrice(price);
       
        
        populateTable();

            JOptionPane.showMessageDialog(this, "Update successful!");
        } else if (tblVehicle.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Table is empty");
        } else {
            JOptionPane.showMessageDialog(this, "Please select single row");
        }
    }//GEN-LAST:event_btnUpdateVehicleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnDeleteVehicle;
    private javax.swing.JButton btnUpdateVehicle;
    private javax.swing.JButton btnViewVehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehicle;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSeater;
    private javax.swing.JTextField txtVehicleName;
    private javax.swing.JTextField txtVehicleNum;
    // End of variables declaration//GEN-END:variables
}
