/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Shopping;

import Business.EcoSystem;
import Business.Shopping.InhouseShopping.Souvenir;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manikantareddythikkavarapu
 */
public class ShopPanel extends javax.swing.JPanel {

    private EcoSystem system;

    String mainValidationString = "";
    String validationString1 = "";
    String validationString2 = "";

    /**
     * Creates new form ShopPanel
     */
    public ShopPanel(EcoSystem system) {
        initComponents();
        this.system = system;
        showSouvenirData();
    }

    private void resetShopData() {
        txtId.setText("");
        txtName.setText("");
        txtPrice.setText("");
    }

    public boolean areDataFieldsEmpty() {
        validationString1 = "";
        if (txtId.getText().isEmpty()) {
            validationString1 += "Id, ";
        }
        if (txtName.getText().isEmpty()) {
            validationString1 += "Name, ";
        }
        if (txtPrice.getText() == null) {
            validationString1 += "Price, ";
        }
        return isNotValid(validationString1);
    }

    public boolean areDataTypesCorrect() {
        validationString2 = "";
        if (!validateDoubleDataType(txtPrice.getText())) {
            validationString2 += "Price, ";
        }
        return isNotValid(validationString2);
    }

    public boolean isNotValid(String str) {
        if (str.equals("")) {
            return false;
        } else {
            return true;
        }
    }

    public boolean validateDoubleDataType(String str) {
        try {
            Double.parseDouble(str);
        } catch (NumberFormatException e) {
            return false;
        }
        return true;
    }

    public void validationErrorMessagesDialog(boolean validation1, boolean validation2) {
        if (validation1) {
            mainValidationString = validationString1;
            JOptionPane.showMessageDialog(this, "Please update the data for these fields: " + mainValidationString);
        } else if (validation2) {
            mainValidationString = validationString2;
            JOptionPane.showMessageDialog(this, "Please enter only numbers for these fields: " + mainValidationString);
        }
    }

    private boolean souvenirDetailsExistence() {
        boolean exist = false;
        for (Souvenir sv : system.getSouvenirDirectory().getSouvenirDirectory()) {
            if (txtId.getText().equals(sv.getSouvenirId())) {
                exist = true;
                break;
            }
        }
        return exist;
    }

    private Souvenir setSouvenirData() {
        String souvenirId = txtId.getText();
        String name = txtName.getText();
        double price = Double.parseDouble(txtPrice.getText());

        Souvenir sv = new Souvenir();
        sv.setSouvenirId(souvenirId);
        sv.setSouvenirName(name);
        sv.setPrice(price);

        return sv;
    }

    private void showSouvenirData() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Souvenir sv : system.getSouvenirDirectory().getSouvenirDirectory()) {

            Object[] newRow = new Object[3];
            newRow[0] = sv;
            newRow[1] = sv.getSouvenirName();
            newRow[2] = sv.getPrice();

            model.addRow(newRow);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(166, 57, 452, 150);

        jLabel1.setText("Shop");
        add(jLabel1);
        jLabel1.setBounds(368, 22, 30, 17);

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(313, 237, 72, 23);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(403, 237, 72, 23);
        add(txtId);
        txtId.setBounds(395, 314, 107, 23);

        jLabel2.setText("Id");
        add(jLabel2);
        jLabel2.setBounds(313, 317, 11, 17);

        jLabel3.setText("Name");
        add(jLabel3);
        jLabel3.setBounds(313, 358, 34, 17);

        jLabel4.setText("Price");
        add(jLabel4);
        jLabel4.setBounds(313, 399, 29, 17);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName);
        txtName.setBounds(395, 355, 107, 23);
        add(txtPrice);
        txtPrice.setBounds(395, 396, 107, 23);

        jButton3.setText("Create");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(313, 449, 72, 23);

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(403, 449, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            boolean validation1 = areDataFieldsEmpty();
            boolean validation2 = areDataTypesCorrect();

            if (!validation1 && !validation2) {
                String souvenirId = txtId.getText();
                if (!souvenirDetailsExistence()) {
                    system.getSouvenirDirectory().addNewSouvenirData(setSouvenirData());
                    JOptionPane.showMessageDialog(this, "New souvenir data with souvenirId id : " + souvenirId + " created");
                    resetShopData();
                    showSouvenirData();
                } else {
                    JOptionPane.showMessageDialog(this, "Souvenir details already exists with the souvenirId : " + souvenirId);
                }
            } else {
                validationErrorMessagesDialog(validation1, validation2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRowIndex = jTable1.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a row to delete.");
                return;
            }
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Souvenir selectedSouvenir = (Souvenir) model.getValueAt(selectedRowIndex, 0);
            system.getSouvenirDirectory().deleteSouvenirData(selectedSouvenir);
            JOptionPane.showMessageDialog(this, "Selected souvenir data deleted");
            resetShopData();
            showSouvenirData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int index = jTable1.getSelectedRow();

            if (index < 0) {
                JOptionPane.showMessageDialog(this, "Please select a row to be viewed");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Souvenir selectedSouvenirItem = (Souvenir) model.getValueAt(index, 0);

            txtId.setText(selectedSouvenirItem.getSouvenirId());
            txtName.setText(selectedSouvenirItem.getSouvenirName());
            txtPrice.setText(String.valueOf(selectedSouvenirItem.getPrice()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            String souvenirId = txtId.getText();
            boolean validation1 = areDataFieldsEmpty();

            if (!validation1) {
                if (souvenirDetailsExistence()) {
                    Souvenir updatedSouvenirData = setSouvenirData();
                    int index = 0;
                    for (Souvenir sv : system.getSouvenirDirectory().getSouvenirDirectory()) {
                        if (souvenirId.equals(sv.getSouvenirId())) {
                            system.getSouvenirDirectory().updateExistingSouvenirData(updatedSouvenirData, index);
                            break;
                        }
                        index++;
                    }
                    JOptionPane.showMessageDialog(this, "Existing souvenir details with souvenir id : " + souvenirId + " updated");
                    resetShopData();
                    showSouvenirData();
                } else {
                    JOptionPane.showMessageDialog(this, "You can't update the souvenir details since menu with souvenir id : " + souvenirId + " doesn't exist");
                }
            } else {
                validationErrorMessagesDialog(validation1, false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
