/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import Business.EcoSystem;
import Business.User.User;

/**
 *
 * @author Subbu
 */
public class CustomerHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerHome
     */
    
    EcoSystem system;
    User user;
    
    public CustomerHomePanel(EcoSystem system, User user) {
        initComponents();
        this.system = system;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        userLeftPanel = new javax.swing.JPanel();
        bookVehicleBtn = new javax.swing.JButton();
        bookPoolBtn = new javax.swing.JButton();
        bookGameBtn = new javax.swing.JButton();
        bookLaundryBtn = new javax.swing.JButton();
        shopBtn = new javax.swing.JButton();
        checkOutBtn = new javax.swing.JButton();
        bookFoodBtn = new javax.swing.JButton();
        userRightPanel = new javax.swing.JPanel();

        bookVehicleBtn.setText("Book Vehicle");
        bookVehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookVehicleBtnActionPerformed(evt);
            }
        });

        bookPoolBtn.setText("Book Pool");

        bookGameBtn.setText("Book Games");

        bookLaundryBtn.setText("Laundry");

        shopBtn.setText("Souvenir Shop");
        shopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopBtnActionPerformed(evt);
            }
        });

        checkOutBtn.setText("Checkout");
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });

        bookFoodBtn.setText("Food and Beverage");
        bookFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFoodBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userLeftPanelLayout = new javax.swing.GroupLayout(userLeftPanel);
        userLeftPanel.setLayout(userLeftPanelLayout);
        userLeftPanelLayout.setHorizontalGroup(
            userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLeftPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shopBtn)
                    .addComponent(bookFoodBtn)
                    .addComponent(bookGameBtn)
                    .addComponent(bookPoolBtn)
                    .addComponent(bookVehicleBtn)
                    .addComponent(bookLaundryBtn)
                    .addComponent(checkOutBtn))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        userLeftPanelLayout.setVerticalGroup(
            userLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLeftPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(bookVehicleBtn)
                .addGap(18, 18, 18)
                .addComponent(bookPoolBtn)
                .addGap(18, 18, 18)
                .addComponent(bookGameBtn)
                .addGap(18, 18, 18)
                .addComponent(bookFoodBtn)
                .addGap(18, 18, 18)
                .addComponent(bookLaundryBtn)
                .addGap(18, 18, 18)
                .addComponent(shopBtn)
                .addGap(43, 43, 43)
                .addComponent(checkOutBtn)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(userLeftPanel);

        javax.swing.GroupLayout userRightPanelLayout = new javax.swing.GroupLayout(userRightPanel);
        userRightPanel.setLayout(userRightPanelLayout);
        userRightPanelLayout.setHorizontalGroup(
            userRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        userRightPanelLayout.setVerticalGroup(
            userRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(userRightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void shopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopBtnActionPerformed
        // Redirect User to Shopping Panel
    }//GEN-LAST:event_shopBtnActionPerformed

    private void bookVehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookVehicleBtnActionPerformed
        // Redirect User to Vehicle Booking Panel
        VehicleBookingPanel bookVehicle = new VehicleBookingPanel(system, user);
        jSplitPane1.setRightComponent(bookVehicle);
    }//GEN-LAST:event_bookVehicleBtnActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        // TODO add your handling code here:
        CheckoutPanel checkout = new CheckoutPanel(system, user);
        jSplitPane1.setRightComponent(checkout);
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void bookFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFoodBtnActionPerformed
        // TODO add your handling code here:
        FoodBookingPanel bookFood = new FoodBookingPanel(system, user);
        jSplitPane1.setRightComponent(bookFood);
    }//GEN-LAST:event_bookFoodBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookFoodBtn;
    private javax.swing.JButton bookGameBtn;
    private javax.swing.JButton bookLaundryBtn;
    private javax.swing.JButton bookPoolBtn;
    private javax.swing.JButton bookVehicleBtn;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton shopBtn;
    private javax.swing.JPanel userLeftPanel;
    private javax.swing.JPanel userRightPanel;
    // End of variables declaration//GEN-END:variables
}
